// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsbajxbprkimcgznlgpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzYmFqeGJwcmtpbWNnem5sZ3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzQ4NTEsImV4cCI6MjA2MTc1MDg1MX0.pmNA-LyLmB-MgWhsThrI73itGpU_GSglheSwLVyd9rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);